[package]
name = "vulkan_tutorial"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
env_logger = "0.11.8"
image = "0.25.6"
log = "0.4.27"
vulkano = "0.35.1"
vulkano-shaders = "0.35.0"

[profile.dev]
opt-level = 1 
